# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(373, 191)
        MainWindow.setStyleSheet("background: url(:/Downloads/TwiceNow.png)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.radMovie = QtWidgets.QRadioButton(self.centralwidget)
        self.radMovie.setGeometry(QtCore.QRect(30, 30, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.radMovie.setFont(font)
        self.radMovie.setObjectName("radMovie")
        self.radBook = QtWidgets.QRadioButton(self.centralwidget)
        self.radBook.setGeometry(QtCore.QRect(210, 30, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.radBook.setFont(font)
        self.radBook.setObjectName("radBook")
        self.buttonExcel = QtWidgets.QPushButton(self.centralwidget)
        self.buttonExcel.setGeometry(QtCore.QRect(50, 90, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonExcel.setFont(font)
        self.buttonExcel.setObjectName("buttonExcel")
        self.buttonCSV = QtWidgets.QPushButton(self.centralwidget)
        self.buttonCSV.setGeometry(QtCore.QRect(210, 90, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonCSV.setFont(font)
        self.buttonCSV.setObjectName("buttonCSV")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 373, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radMovie.setText(_translate("MainWindow", "IMDb top 1000"))
        self.radBook.setText(_translate("MainWindow", "Book Scraper"))
        self.buttonExcel.setText(_translate("MainWindow", "Export to Excel"))
        self.buttonCSV.setText(_translate("MainWindow", "Export to CSV"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
